name: React/Electron CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Format check with Prettier
        run: npm run format:check

      - name: Lint with ESLint
        run: npm run lint

      - name: Build and type check
        run: npm run build
